package com.zhousl.aether.ui

import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.animateContentSize
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.rounded.ArrowForwardIos
import androidx.compose.material.icons.rounded.ArrowDropDown
import androidx.compose.material.icons.rounded.Check
import androidx.compose.material.icons.rounded.Refresh
import androidx.compose.material.icons.rounded.Visibility
import androidx.compose.material.icons.rounded.VisibilityOff
import androidx.compose.material3.Checkbox
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.DropdownMenu
import androidx.compose.material3.DropdownMenuItem
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.Stable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.Saver
import androidx.compose.runtime.saveable.listSaver
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.text.TextRange
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.TextFieldValue
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.unit.dp
import com.zhousl.aether.data.AppLanguage
import com.zhousl.aether.data.LlmProvider
import com.zhousl.aether.data.LlmProviderConfig
import com.zhousl.aether.data.isProviderSetupValid
import com.zhousl.aether.data.isValidProviderId
import com.zhousl.aether.data.requiresApiKey
import com.zhousl.aether.data.sanitizeProviderId
import com.zhousl.aether.ui.theme.AetherOnSurface
import com.zhousl.aether.ui.theme.AetherOnSurfaceVariant
import com.zhousl.aether.ui.theme.AetherSurface
import com.zhousl.aether.ui.theme.AetherSurfaceHigh
import java.util.UUID

private val ProviderFormPrimary = Color(0xFF5C5C5C)

@Stable
class ProviderFormState internal constructor(
    private val existingConfig: LlmProviderConfig?,
    providerId: String,
    name: String,
    providerStorageValue: String,
    apiKey: String,
    baseUrl: String,
    modelId: String,
    userAgent: String,
    cachedModels: List<String>,
    enabledModelIds: List<String>,
    basicFunctionCallingCompatibilityMode: Boolean,
    providerIdManuallyEdited: Boolean = existingConfig != null,
    lastAutoGeneratedProviderId: String = providerId,
) {
    var providerId by mutableStateOf(providerId)
    var name by mutableStateOf(name)
    var providerStorageValue by mutableStateOf(providerStorageValue)
    var apiKey by mutableStateOf(apiKey)
    var baseUrl by mutableStateOf(baseUrl)
    var modelId by mutableStateOf(modelId)
    var userAgent by mutableStateOf(userAgent)
    var cachedModels by mutableStateOf(cachedModels)
    var enabledModelIds by mutableStateOf(enabledModelIds)
    var basicFunctionCallingCompatibilityMode by mutableStateOf(basicFunctionCallingCompatibilityMode)
    var isFetchingModelsLocally by mutableStateOf(false)
    private var providerIdManuallyEdited by mutableStateOf(providerIdManuallyEdited)
    private var lastAutoGeneratedProviderId by mutableStateOf(lastAutoGeneratedProviderId)

    val selectedProvider: LlmProvider
        get() = LlmProvider.fromStorage(providerStorageValue)

    val allModels: List<String>
        get() = (cachedModels + modelId)
            .map(String::trim)
            .filter(String::isNotEmpty)
            .distinct()

    val effectiveModelId: String
        get() = enabledModelIds.firstOrNull()
            ?: modelId.trim().ifBlank { allModels.firstOrNull().orEmpty() }

    val isCurrentlyEnabled: Boolean
        get() = existingConfig?.isEnabled ?: true

    val isProviderIdManuallyEdited: Boolean
        get() = providerIdManuallyEdited

    val currentAutoGeneratedProviderId: String
        get() = lastAutoGeneratedProviderId

    fun updateName(value: String) {
        name = value
        updateAutoGeneratedProviderId()
    }

    fun setProviderIdFromUser(value: String) {
        providerId = value
        providerIdManuallyEdited = value.isNotBlank() && value != lastAutoGeneratedProviderId
    }

    fun isValid(existingProviderIds: Set<String>): Boolean {
        val normalizedProviderId = normalizedProviderId
        val normalizedExistingProviderIds = existingProviderIds.map { it.trim().sanitizeProviderId() }.toSet()
        val providerIdAvailable = normalizedProviderId !in (normalizedExistingProviderIds - setOf(existingProviderId))
        return providerIdAvailable &&
            isValidProviderId(normalizedProviderId) &&
            isProviderSetupValid(
                provider = selectedProvider,
                apiKey = apiKey,
                baseUrl = baseUrl,
                modelId = effectiveModelId,
            )
    }

    fun applyProviderDefaults(newProvider: LlmProvider) {
        val previousProvider = selectedProvider
        providerStorageValue = newProvider.storageValue
        if (baseUrl.isBlank() || baseUrl.trim() == previousProvider.defaultBaseUrl) {
            baseUrl = newProvider.defaultBaseUrl
        }
        if (modelId.isBlank() || modelId.trim() == previousProvider.defaultModelId) {
            modelId = newProvider.defaultModelId
        }
        if (!providerIdManuallyEdited) {
            updateAutoGeneratedProviderId()
        } else if (providerId.isBlank() || providerId.trim() == previousProvider.storageValue) {
            providerId = newProvider.storageValue
        }
    }

    private fun updateAutoGeneratedProviderId() {
        if (providerIdManuallyEdited) return
        val generatedProviderId = name.sanitizeProviderId().ifBlank { selectedProvider.storageValue }
        providerId = generatedProviderId
        lastAutoGeneratedProviderId = generatedProviderId
    }

    fun setModelEnabled(
        model: String,
        enabled: Boolean,
    ) {
        enabledModelIds = if (enabled) {
            (enabledModelIds + model).map(String::trim).filter(String::isNotEmpty).distinct()
        } else {
            enabledModelIds.filterNot { it == model }
        }
    }

    /**
     * 批量更新当前可见模型的启用状态，避免逐项写入造成重复重组。
     */
    fun setAllModelsEnabled(
        models: List<String>,
        enabled: Boolean,
    ) {
        val normalizedModels = models
            .map(String::trim)
            .filter(String::isNotEmpty)
            .distinct()
        enabledModelIds = if (enabled) {
            normalizedModels
        } else {
            emptyList()
        }
    }

    /**
     * 应用远端拉取的模型列表，并在空结果时保留当前本地模型配置。
     */
    fun applyFetchedModels(models: List<String>) {
        val normalizedCurrent = allModels.toSet()
        val normalizedModels = models
            .map(String::trim)
            .filter(String::isNotEmpty)
            .distinct()
        if (normalizedModels.isEmpty()) return
        val previouslyEnabledModels = enabledModelIds.toSet()
        cachedModels = normalizedModels
        enabledModelIds = normalizedModels.filter { model ->
            previouslyEnabledModels.contains(model) || !normalizedCurrent.contains(model)
        }
        if (normalizedModels.isNotEmpty() && (modelId.trim().isBlank() || normalizedModels.none { it == modelId.trim() })) {
            modelId = normalizedModels.firstOrNull().orEmpty()
        }
    }

    /**
     * 构建可持久化的 Provider 配置，并复用模型集合以减少重复列表扫描。
     */
    fun buildConfig(): LlmProviderConfig {
        val normalizedModels = allModels
        val normalizedModelSet = normalizedModels.toSet()
        return LlmProviderConfig(
            id = existingConfig?.id ?: UUID.randomUUID().toString(),
            providerId = normalizedProviderId,
            name = name.trim().ifBlank { selectedProvider.displayName },
            providerType = selectedProvider,
            apiKey = apiKey.trim(),
            baseUrl = baseUrl.trim(),
            modelId = effectiveModelId.ifBlank { selectedProvider.defaultModelId },
            userAgent = userAgent.trim(),
            cachedModels = normalizedModels,
            enabledModelIds = enabledModelIds
                .map(String::trim)
                .filter { it.isNotEmpty() && normalizedModelSet.contains(it) }
                .distinct(),
            isEnabled = existingConfig?.isEnabled ?: true,
            basicFunctionCallingCompatibilityMode = basicFunctionCallingCompatibilityMode,
            createdAtMillis = existingConfig?.createdAtMillis ?: System.currentTimeMillis(),
        )
    }

    val normalizedProviderId: String
        get() = providerId.trim().sanitizeProviderId()

    val existingProviderId: String
        get() = existingConfig?.providerId.orEmpty().trim().sanitizeProviderId()
 
    companion object {
        fun fromConfig(existingConfig: LlmProviderConfig?): ProviderFormState {
            val initialProvider = existingConfig?.providerType ?: LlmProvider.OpenAiCompatible
            val initialModelId = existingConfig?.modelId ?: initialProvider.defaultModelId
            val initialModels = (existingConfig?.cachedModels.orEmpty() + initialModelId)
                .map(String::trim)
                .filter(String::isNotEmpty)
                .distinct()
            val initialEnabledModels = if (existingConfig != null) {
                existingConfig.enabledModelIds
                    .map(String::trim)
                    .filter { it.isNotEmpty() && initialModels.contains(it) }
                    .distinct()
            } else {
                listOf(initialModelId)
            }
            return ProviderFormState(
                existingConfig = existingConfig,
                providerId = existingConfig?.providerId ?: initialProvider.storageValue,
                name = existingConfig?.name.orEmpty(),
                providerStorageValue = initialProvider.storageValue,
                apiKey = existingConfig?.apiKey.orEmpty(),
                baseUrl = existingConfig?.baseUrl ?: initialProvider.defaultBaseUrl,
                modelId = initialModelId,
                userAgent = existingConfig?.userAgent.orEmpty(),
                cachedModels = initialModels,
                enabledModelIds = initialEnabledModels,
                basicFunctionCallingCompatibilityMode =
                    existingConfig?.basicFunctionCallingCompatibilityMode ?: false,
            )
        }
    }
}

@Composable
fun rememberProviderFormState(
    existingConfig: LlmProviderConfig?,
): ProviderFormState = rememberSaveable(
    existingConfig?.id,
    saver = providerFormStateSaver(existingConfig),
) {
    ProviderFormState.fromConfig(existingConfig)
}

@Composable
fun ProviderConfigurationForm(
    state: ProviderFormState,
    existingProviderIds: Set<String>,
    isFetchingModels: Boolean,
    onFetchModels: (LlmProviderConfig, (List<String>) -> Unit) -> Unit,
    modifier: Modifier = Modifier,
    cardColor: Color = AetherSurfaceHigh,
) {
    val strings = rememberAetherStrings()
    val selectedProvider = state.selectedProvider
    val normalizedProviderId = state.normalizedProviderId
    val existingProviderId = state.existingProviderId
    val normalizedExistingProviderIds = existingProviderIds.map { it.trim().sanitizeProviderId() }.toSet()
    val providerIdAlreadyUsed = normalizedProviderId in (normalizedExistingProviderIds - setOf(existingProviderId))
    val providerIdError = when {
        normalizedProviderId.isBlank() -> providerFormTr(strings, "Provider ID is required.", "Provider ID 不能为空。")
        !isValidProviderId(normalizedProviderId) -> providerFormTr(strings, "Use lowercase letters, numbers, and underscores only.", "仅可使用小写字母、数字和下划线。")
        providerIdAlreadyUsed -> providerFormTr(strings, "This provider ID is already in use.", "此 Provider ID 已被使用。")
        else -> ""
    }
    var apiKeyVisible by rememberSaveable { mutableStateOf(false) }
    var advancedExpanded by rememberSaveable { mutableStateOf(false) }

    Column(
        modifier = modifier.fillMaxWidth(),
        verticalArrangement = Arrangement.spacedBy(16.dp),
    ) {
        ProviderFormCard(cardColor = cardColor) {
            ProviderFormTextField(
                label = providerFormTr(strings, "Provider name", "Provider 名称"),
                value = state.name,
                onValueChange = state::updateName,
            )
            ProviderFormDivider()
            ProviderFormTextField(
                label = "Provider ID",
                value = state.providerId,
                onValueChange = state::setProviderIdFromUser,
            )
        }

        if (providerIdError.isNotBlank()) {
            Text(
                text = providerIdError,
                style = MaterialTheme.typography.bodySmall,
                color = Color(0xFFD25757),
                modifier = Modifier.padding(horizontal = 4.dp),
            )
        }

        ProviderFormCard(cardColor = cardColor) {
            ProviderFormDropdownField(
                label = providerFormTr(strings, "Request format", "请求格式"),
                selectedValue = selectedProvider.displayName,
                options = LlmProvider.entries,
                onSelected = state::applyProviderDefaults,
            )
        }

        Text(
            text = when (selectedProvider) {
                LlmProvider.OpenAiResponses -> providerFormTr(strings, "Use OpenAI-compatible /responses endpoints.", "使用 OpenAI 兼容的 /responses 端点。")
                LlmProvider.OpenAiCompatible -> providerFormTr(strings, "Use OpenAI-compatible /chat/completions endpoints.", "使用 OpenAI 兼容的 /chat/completions 端点。")
                LlmProvider.VertexExpress -> providerFormTr(strings, "Use Vertex AI Express Mode generateContent.", "使用 Vertex AI Express Mode generateContent。")
                LlmProvider.AnthropicMessages -> providerFormTr(strings, "Use Anthropic-compatible /messages endpoints.", "使用 Anthropic 兼容的 /messages 端点。")
            },
            style = MaterialTheme.typography.bodySmall,
            color = AetherOnSurfaceVariant,
            modifier = Modifier.padding(horizontal = 4.dp),
        )

        ProviderFormCard(cardColor = cardColor) {
            ProviderFormTextField(
                label = "API Key",
                value = state.apiKey,
                onValueChange = { state.apiKey = it },
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password),
                visualTransformation = if (apiKeyVisible) VisualTransformation.None else PasswordVisualTransformation(),
                trailingContent = {
                    IconButton(onClick = { apiKeyVisible = !apiKeyVisible }) {
                        Icon(
                            imageVector = if (apiKeyVisible) Icons.Rounded.VisibilityOff else Icons.Rounded.Visibility,
                            contentDescription = if (apiKeyVisible) {
                                providerFormTr(strings, "Hide API key", "隐藏 API Key")
                            } else {
                                providerFormTr(strings, "Show API key", "显示 API Key")
                            },
                            tint = AetherOnSurfaceVariant,
                        )
                    }
                },
            )
            ProviderFormDivider()
            ProviderFormTextField(
                label = "Base URL",
                value = state.baseUrl,
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Uri),
                onValueChange = { state.baseUrl = it },
            )
            ProviderFormDivider()
            ProviderFormTextField(
                label = providerFormTr(strings, "Manual model ID", "手动模型 ID"),
                value = state.modelId,
                onValueChange = { state.modelId = it },
            )
            ProviderFormDivider()
            ProviderModelListField(
                models = state.allModels,
                enabledModelIds = state.enabledModelIds,
                isFetchingModels = state.isFetchingModelsLocally || isFetchingModels,
                onToggleModel = state::setModelEnabled,
                onToggleAllModels = { enabled ->
                    state.setAllModelsEnabled(state.allModels, enabled)
                },
                onFetchModels = {
                    state.isFetchingModelsLocally = true
                    runCatching {
                        onFetchModels(state.buildConfig()) { models ->
                            state.applyFetchedModels(models)
                            state.isFetchingModelsLocally = false
                        }
                    }.onFailure {
                        state.isFetchingModelsLocally = false
                    }
                },
            )
        }

        SettingsExpandablePanel(
            title = "Advanced",
            subtitle = providerFormTr(strings, "Compatibility and request header overrides", "兼容性与请求头覆盖"),
            expanded = advancedExpanded,
            onExpandedChange = { advancedExpanded = it },
        ) {
            ProviderCompatibilityModeField(
                enabled = state.basicFunctionCallingCompatibilityMode,
                onEnabledChange = { state.basicFunctionCallingCompatibilityMode = it },
            )
            ProviderFormTextField(
                label = "User-Agent",
                value = state.userAgent,
                onValueChange = { state.userAgent = it },
            )
        }

        Text(
            text = if (selectedProvider.requiresApiKey(state.baseUrl)) {
                providerFormTr(strings, "Enabled models appear in the chat model picker. This request format requires an API key.", "已启用模型会显示在聊天模型选择器中。此请求格式需要 API Key。")
            } else {
                providerFormTr(strings, "Enabled models appear in the chat model picker. Refresh loads models from the provider API.", "已启用模型会显示在聊天模型选择器中。刷新会从 Provider API 加载模型。")
            },
            style = MaterialTheme.typography.bodySmall,
            color = AetherOnSurfaceVariant,
            modifier = Modifier.padding(horizontal = 4.dp),
        )
    }
}

private fun providerFormStateSaver(
    existingConfig: LlmProviderConfig?,
): Saver<ProviderFormState, Any> = listSaver(
    save = { state ->
        listOf(
            state.providerId,
            state.name,
            state.providerStorageValue,
            state.apiKey,
            state.baseUrl,
            state.modelId,
            state.userAgent,
            state.cachedModels,
            state.enabledModelIds,
            state.basicFunctionCallingCompatibilityMode,
            state.isProviderIdManuallyEdited,
            state.currentAutoGeneratedProviderId,
        )
    },
    restore = { restored ->
        @Suppress("UNCHECKED_CAST")
        val hasSavedUserAgent = restored.getOrNull(6) is String
        ProviderFormState(
            existingConfig = existingConfig,
            providerId = restored[0] as String,
            name = restored[1] as String,
            providerStorageValue = restored[2] as String,
            apiKey = restored[3] as String,
            baseUrl = restored[4] as String,
            modelId = restored[5] as String,
            userAgent = if (hasSavedUserAgent) restored[6] as String else existingConfig?.userAgent.orEmpty(),
            cachedModels = restored[if (hasSavedUserAgent) 7 else 6] as List<String>,
            enabledModelIds = restored[if (hasSavedUserAgent) 8 else 7] as List<String>,
            basicFunctionCallingCompatibilityMode = restored.getOrNull(if (hasSavedUserAgent) 9 else 8) as? Boolean
                ?: existingConfig?.basicFunctionCallingCompatibilityMode
                ?: false,
            providerIdManuallyEdited = restored.getOrNull(if (hasSavedUserAgent) 10 else 9) as? Boolean ?: (existingConfig != null),
            lastAutoGeneratedProviderId = restored.getOrNull(if (hasSavedUserAgent) 11 else 10) as? String ?: restored[0] as String,
        )
    },
)

/**
 * 根据当前应用语言返回 Provider 表单文案。
 */
private fun providerFormTr(strings: AetherStrings, english: String, chinese: String): String =
    if (strings.appLanguage == AppLanguage.SimplifiedChinese) chinese else english

@Composable
private fun ProviderCompatibilityModeField(
    enabled: Boolean,
    onEnabledChange: (Boolean) -> Unit,
) {
    val strings = rememberAetherStrings()
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clickable { onEnabledChange(!enabled) }
            .padding(horizontal = 16.dp, vertical = 14.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween,
    ) {
        Column(modifier = Modifier.weight(1f)) {
            Text(
                text = providerFormTr(strings, "Basic tool compatibility", "基础工具兼容"),
                style = MaterialTheme.typography.bodyLarge,
                color = AetherOnSurface,
            )
            Spacer(modifier = Modifier.height(4.dp))
            Text(
                text = if (enabled) providerFormTr(strings, "On", "开启") else providerFormTr(strings, "Off", "关闭"),
                style = MaterialTheme.typography.bodySmall,
                color = AetherOnSurfaceVariant,
            )
        }
        Switch(
            checked = enabled,
            onCheckedChange = onEnabledChange,
        )
    }
}

@Composable
private fun ProviderFormCard(
    cardColor: Color,
    content: @Composable () -> Unit,
) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .background(cardColor, RoundedCornerShape(20.dp)),
    ) {
        content()
    }
}

@Composable
private fun ProviderFormDivider() {
    Spacer(modifier = Modifier.height(8.dp))
}

@Composable
private fun ProviderFormTextField(
    label: String,
    value: String,
    onValueChange: (String) -> Unit,
    modifier: Modifier = Modifier,
    keyboardOptions: KeyboardOptions = KeyboardOptions.Default,
    visualTransformation: VisualTransformation = VisualTransformation.None,
    trailingContent: (@Composable () -> Unit)? = null,
) {
    var fieldValue by rememberSaveable(label, stateSaver = TextFieldValue.Saver) {
        mutableStateOf(TextFieldValue(value, selection = TextRange(value.length)))
    }

    LaunchedEffect(value) {
        if (value != fieldValue.text) {
            fieldValue = TextFieldValue(value, selection = TextRange(value.length))
        }
    }

    Column(
        modifier = modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp, vertical = 14.dp),
    ) {
        Text(
            text = label,
            style = MaterialTheme.typography.bodySmall,
            color = AetherOnSurfaceVariant,
        )
        Spacer(modifier = Modifier.height(6.dp))
        BasicTextField(
            value = fieldValue,
            onValueChange = {
                fieldValue = it
                onValueChange(it.text)
            },
            modifier = Modifier.fillMaxWidth(),
            textStyle = MaterialTheme.typography.bodyLarge.copy(color = AetherOnSurface),
            cursorBrush = SolidColor(ProviderFormPrimary),
            keyboardOptions = keyboardOptions,
            visualTransformation = visualTransformation,
            decorationBox = { innerTextField ->
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    verticalAlignment = Alignment.CenterVertically,
                ) {
                    Box(modifier = Modifier.weight(1f)) {
                        if (fieldValue.text.isEmpty()) {
                            Text(
                                text = label,
                                style = MaterialTheme.typography.bodyLarge,
                                color = AetherOnSurfaceVariant.copy(alpha = 0.5f),
                            )
                        }
                        innerTextField()
                    }
                    trailingContent?.invoke()
                }
            },
        )
    }
}

@Composable
private fun ProviderFormDropdownField(
    label: String,
    selectedValue: String,
    options: List<LlmProvider>,
    onSelected: (LlmProvider) -> Unit,
) {
    val strings = rememberAetherStrings()
    var expanded by remember { mutableStateOf(false) }

    Column(
        modifier = Modifier
            .fillMaxWidth()
            .clickable { expanded = true }
            .padding(horizontal = 16.dp, vertical = 14.dp),
    ) {
        Text(
            text = label,
            style = MaterialTheme.typography.bodySmall,
            color = AetherOnSurfaceVariant,
        )
        Spacer(modifier = Modifier.height(4.dp))
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Text(
                text = selectedValue,
                style = MaterialTheme.typography.bodyLarge,
                color = AetherOnSurface,
            )
            Icon(
                imageVector = Icons.Rounded.ArrowDropDown,
                contentDescription = providerFormTr(strings, "Choose provider", "选择 Provider"),
                tint = AetherOnSurfaceVariant,
            )
        }
        DropdownMenu(
            expanded = expanded,
            onDismissRequest = { expanded = false },
            modifier = Modifier.background(AetherSurface),
        ) {
            options.forEach { option ->
                DropdownMenuItem(
                    text = { Text(option.displayName, color = AetherOnSurface) },
                    trailingIcon = if (option.displayName == selectedValue) {
                        { Icon(Icons.Rounded.Check, contentDescription = null, tint = ProviderFormPrimary) }
                    } else {
                        null
                    },
                    onClick = {
                        expanded = false
                        onSelected(option)
                    },
                )
            }
        }
    }
}

@Composable
private fun ProviderModelListField(
    models: List<String>,
    enabledModelIds: List<String>,
    isFetchingModels: Boolean,
    onToggleModel: (String, Boolean) -> Unit,
    onToggleAllModels: (Boolean) -> Unit,
    onFetchModels: () -> Unit,
) {
    val strings = rememberAetherStrings()
    val enabledModelIdSet = remember(enabledModelIds) { enabledModelIds.toSet() }
    val enabledVisibleModelCount = remember(models, enabledModelIdSet) {
        models.count(enabledModelIdSet::contains)
    }
    val allModelsEnabled = models.isNotEmpty() && enabledVisibleModelCount == models.size

    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp, vertical = 14.dp),
    ) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.SpaceBetween,
        ) {
            Column(modifier = Modifier.weight(1f)) {
                Text(
                    text = providerFormTr(strings, "Model list", "模型列表"),
                    style = MaterialTheme.typography.bodySmall,
                    color = AetherOnSurfaceVariant,
                )
                Spacer(modifier = Modifier.height(4.dp))
                Text(
                    text = if (models.isEmpty()) {
                        providerFormTr(strings, "No models loaded yet.", "尚未加载模型。")
                    } else {
                        providerFormTr(strings, "$enabledVisibleModelCount/${models.size} enabled", "已启用 $enabledVisibleModelCount/${models.size}")
                    },
                    style = MaterialTheme.typography.bodyMedium,
                    color = AetherOnSurface,
                )
            }
            if (isFetchingModels) {
                CircularProgressIndicator(
                    modifier = Modifier.size(24.dp),
                    strokeWidth = 2.dp,
                    color = ProviderFormPrimary,
                )
            } else {
                IconButton(onClick = onFetchModels) {
                    Icon(
                        imageVector = Icons.Rounded.Refresh,
                        contentDescription = providerFormTr(strings, "Fetch models", "获取模型"),
                        tint = ProviderFormPrimary,
                    )
                }
            }
        }

        if (models.isNotEmpty()) {
            Spacer(modifier = Modifier.height(10.dp))
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .clip(RoundedCornerShape(16.dp))
                    .clickable { onToggleAllModels(!allModelsEnabled) }
                    .padding(horizontal = 2.dp, vertical = 6.dp),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                Checkbox(
                    checked = allModelsEnabled,
                    onCheckedChange = { checked -> onToggleAllModels(checked) },
                )
                Spacer(modifier = Modifier.width(8.dp))
                Text(
                    text = if (allModelsEnabled) {
                        providerFormTr(strings, "Clear all models", "清空全部模型")
                    } else {
                        providerFormTr(strings, "Select all models", "选择全部模型")
                    },
                    style = MaterialTheme.typography.bodyMedium,
                    color = AetherOnSurface,
                )
            }
            Spacer(modifier = Modifier.height(4.dp))
            LazyColumn(
                modifier = Modifier
                    .fillMaxWidth()
                    .heightIn(max = 320.dp),
                contentPadding = PaddingValues(vertical = 2.dp),
                verticalArrangement = Arrangement.spacedBy(6.dp),
            ) {
                items(models, key = { it }) { model ->
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .clickable { onToggleModel(model, !enabledModelIdSet.contains(model)) }
                            .padding(vertical = 2.dp),
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        Checkbox(
                            checked = enabledModelIdSet.contains(model),
                            onCheckedChange = { checked -> onToggleModel(model, checked) },
                        )
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(
                            text = model,
                            style = MaterialTheme.typography.bodyMedium,
                            color = AetherOnSurface,
                        )
                    }
                }
            }
        }
    }
}
